Update patch set 1
Patch Set 1:

The main reason for using the approach I did is that -fPIE -pie is only needed for executables. Shared libraries are already PIE/PIC code by default. With this approach only qemu needed tweaking.

Also, using "LOCAL_NO_DEFAULT_COMPILER_FLAGS := true" in liblog results in:

host C: liblog <= system/core/liblog/logd_write.c
system/core/liblog/logd_write.c:30:24: fatal error: log/logger.h: No such file or directory
compilation terminated.
make: *** [out/host/linux-x86/obj/STATIC_LIBRARIES/liblog_intermediates/logd_write.o] Error 1

Presumably this is because this (and likely other sub-projects) rely on these global definitions.

Joshua

Patch-set: 1